### PR TITLE
#62: Fixed identifier quoting for PostgreSQL and MySQL

### LINKED ISSUE #62: MySqL and PostgreSQL dialect are not injection safe
Currewntly the MySQL and PostgreSQL Identifier allow SQL injection:
```java
System.out.println(MySQLIdentifier.of("test`, `asdf`, `other").quote());
```
--> ``` `test`, `asdf`, `other` ```

### PR DESCRIPTION
**Pull request by jakobbraun**
Closes #62

### CODE REVIEW

File: src/test/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlDatabaseObjectCreationAndDeletionIT.java [hunk 1]
```diff
@@ -40,25 +40,31 @@ private ExistsInDatabaseMatcher(final Connection connection) {
...
                 throw new AssertionError("Unable to determine existence of object: " + object.getName(), exception);
             }
         }
 
+        private boolean matchResult(final DatabaseObject object, final PreparedStatement objectExistenceStatement)
+                throws SQLException {
+            try (final ResultSet resultSet = objectExistenceStatement.executeQuery()) {
+                return resultSet.next() && resultSet.getString(1).equals(object.getName());
+            }
+        }
```
Comment (morazow) [inline src/test/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlDatabaseObjectCreationAndDeletionIT.java:56]: Let's unify inner matcher class, and remove duplication of these two methods.

File: src/test/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlDatabaseObjectCreationAndDeletionIT.java [hunk 2]
```diff
@@ -40,25 +40,31 @@ private ExistsInDatabaseMatcher(final Connection connection) {
...
-                return "SELECT table_name FROM information_schema.tables WHERE table_name = '" + table.getName() + "'";
+                return "SELECT table_name FROM information_schema.tables WHERE table_name = ?";
             } else if (object instanceof Schema) {
                 final Schema schema = (Schema) object;
-                return "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = '" + schema.getName()
-                        + "'";
+                return "SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = ?";
             } else {
                 throw new AssertionError("Assertion for " + object.getType() + " is not yet implemented.");
             }
```
Comment (morazow) [inline src/test/java/com/exasol/dbbuilder/dialects/postgres/PostgreSqlDatabaseObjectCreationAndDeletionIT.java:70]: I think, the `getCheckCommand` can also be unified by taking the `dialect` name as a parameter to the class. Since these all constant strings, predefine them for each dialect.

**Review by morazow — CHANGES_REQUESTED** [review]

**Review by morazow — APPROVED** [review]
